<a href="https://colab.research.google.com/github/Hemant051/Artificial-Neural-Netwrok/blob/main/Hopefield_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


class Hopfield:
    def __init__(self, inp_vector) -> None:
        self.theta = 0
        self.vector_len = len(inp_vector)
        self.inp_vector = self.transform('BIPOLAR', inp_vector)
        self.weight = np.zeros([self.vector_len, self.vector_len])

    def transform(self, mode, vector):
        vector = np.array(vector)
        if mode == 'BIPOLAR':
            vector[vector == 0] = -1
        elif mode == 'BINARY':
            vector[vector == -1] = 0
        return vector

    def activation(self, vector):
        vector[vector > self.theta] = 1
        vector[vector == self.theta] = self.theta
        vector[vector < self.theta] = 0
        return vector

    def set_weight(self):
        first = self.inp_vector.reshape(self.vector_len, 1)
        second = self.inp_vector.reshape(1, self.vector_len)
        self.weight = np.dot(first, second)

    def tune_test(self, vector):
        vector = self.transform('BIPOLAR', vector)
        tune_vector = vector.copy()
        for i in range(self.vector_len):
            weight = self.weight[:, i].reshape(self.vector_len, 1)
            res = vector[i] + np.dot(tune_vector, weight)
            tune_vector[i] = self.activation(res)[0]
        return self.activation(np.dot(tune_vector, self.weight))


model = Hopfield(inp_vector=[1, 0, 1, 1])
model.set_weight()

sample = [[0, 1, 1, 1],
          [1, 1, 0, 1],
          [1, 0, 0, 0],
          [0, 0, 1, 0]]

for item in sample:
    print(model.tune_test(item))

[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
