<a href="https://colab.research.google.com/github/Hemant051/Artificial-Neural-Netwrok/blob/main/Perceptron%20training%20algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn.datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
%matplotlib inline

In [ ]:
# load the breast cancer dataset
breast_cancer = sklearn.datasets.load_breast_cancer()
feature = pd.DataFrame(breast_cancer.data, columns = breast_cancer.feature_names)
label = breast_cancer.target
feature

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [ ]:
feature.shape

(569, 30)

In [ ]:
label.shape

(569,)

In [ ]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mnscaler = MinMaxScaler()
feature = mnscaler.fit_transform(feature)

In [ ]:
lr = 1
w = np.ones(feature.shape[1])
b = 0
accuracy = {}
max_accuracy = 0
wt_matrix = []
wt_matrix.append(w)
epochs = 100
sim = []

In [ ]:
w

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
w.shape

(30,)

In [ ]:
for j in range(1,epochs):
    for i in range(feature.shape[0]):
        yin=np.dot(w,feature[i])
        if yin>=b:
            y_pred=1
        else:
            y_pred=0
        if label[i] == 1 and y_pred == 0:
            w = w + lr * feature[i]
        elif label[i] == 0 and y_pred == 1:
            w = w - lr * feature[i]
    wt_matrix.append(w)
    cos_sim = cosine_similarity(wt_matrix[j-1].reshape(1,-1),wt_matrix[j].reshape(1,-1))
    sim.append(cos_sim)
h_matching=sim.index(max(sim))
final_weight=wt_matrix[h_matching]

In [ ]:
final_weight

array([ 17.05083061,  -2.20865742,  13.4193214 ,  -7.96805938,
         3.19220005,  -3.82559352, -14.18150187, -12.48957753,
         7.58585859,  13.02169334,  -7.4270143 ,   2.79466496,
        -1.94468266, -13.48851509,  -5.07930788,   0.73299636,
         6.88659343,   0.77224853,   7.03208195,   8.54677459,
        -2.00305941,  -2.00506397,  -0.67851985, -19.71401888,
         3.06035792,  -0.95033521,   2.58816853,   1.31762543,
        -9.58170708,  -5.92535747])

In [ ]:
import numpy as np
a=np.array([1,2,3])
a=a.reshape(1,-1)
b=np.array([5,7,9])
b=b.reshape(1,-1)

In [ ]:
a

array([[1, 2, 3]])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
x=cosine_similarity(a,b)
print(x)

[[0.98747922]]
